### PR TITLE
vdiff to handle various other projects

### PR DESCRIPTION
**Pull request by elakito**
Hi Tracey,
we talked about this change about a half year ago.
This patched version uses some heuristics to do the right look up so that it can look up not just a few apache projects at github but some others such as atmosphere and async-http-client. Basically, any project does defines the version constants in its root pom.xml or in its parent/pom.xml can be queried.
I am using it now to look up cxf and those other projects.

In short, you can use the queries like

/version-diff/?repo/proj

where repo is the repository name like "apache", "AsyncHttpClient", "atmosphere", or even your repo name. And proj is the project name like "camel", "cxf", "atmosphere", etc. Both repo and proj parameters can be omitted and in this case, these values are set to apache and camel by default, respectively.

So, for looking up camel, you can use one of the following queries
/version-diff/
/version-diff/?camel
/version-diff/?apache/camel

For looking up cxf, you can use
/version-diff/?cxf
/version-diff/?apache/cxf

For looking up atmosphere, you can use
/version-diff/?Atmosphere/atmosphere

I was wondering if you could merge the change into your repo and put it up at your http server so that we can all use this service. That would be great.

Thanks.
Regards, Aki

### CODE REVIEW

**Comment by tjsnell** [comment]
I completely forgot! Had wanted to do it before your patch. I’ll work on merging it in and deploying it.

Thanks.

**Comment by elakito** [comment]
Hi Tracy,
No problem. Thanks for looking into it.

I forgot to mention that some changes were intended for my local copy which
I had been using ;-). (my readme mentioning the code was forked from your
repo and i commented out the google statistic call in my js copy). Please
feel free to override/adjust these changes according to your needs.

thanks.

regards, aki

2014-07-26 4:12 GMT+02:00 Tracy Snell notifications@github.com:

> I completely forgot! Had wanted to do it before your patch. I’ll work on
> merging it in and deploying it.
> 
> Thanks.
>

**Comment by tjsnell** [comment]
Integrated your patch with a few changes and pushed it back out to GitHub. Seems to be working well. I’ll deploy and post a blog entry. Hopefully tomorrow but I’m traveling so may be Thursday. 

Thanks! I wanted to do this and never got around to it. Love the filters on the versions when one is selected. Nice touch.

tjs

**Comment by elakito** [comment]
Hi Tracy,
glad to hear that you liked the change.
And thank you for writing this useful service and offering it to the
community. ;-)

regards, aki

2014-07-30 4:20 GMT+02:00 Tracy Snell notifications@github.com:

> Integrated your patch with a few changes and pushed it back out to GitHub.
> Seems to be working well. I’ll deploy and post a blog entry. Hopefully
> tomorrow but I’m traveling so may be Thursday.
> 
> Thanks! I wanted to do this and never got around to it. Love the filters
> on the versions when one is selected. Nice touch.
> 
> tjs
>

**Comment by tjsnell** [comment]
It’s deployed and running. Note that I did switch to letting Angular handle the URL parameters. You can link to a specific comparison like this now:

http://vdiff.notsoclever.cc/index.html#Atmosphere/atmosphere/project-2.1.0/project-2.2.0-RC3

**Comment by elakito** [comment]
cool. That direct url reference is very practical. ;-)

2014-07-31 20:15 GMT+02:00 Tracy Snell notifications@github.com:

> It’s deployed and running. Note that I did switch to letting Angular
> handle the URL parameters. You can link to a specific comparison like this
> now:
> 
> http://vdiff.notsoclever.cc/index.html#Atmosphere/atmosphere/project-2.1.0/project-2.2.0-RC3
>

**Comment by tjsnell** [comment]
OK, I’ve revamped it a bunch.

Saner URLS  /diff/{org}/{project} and /diff/{org}/{project}/{v1}/{v2}  No more hash mess (though this did goof up the ability to run local not in the http root.
Trunk is now included in the tags list. However, projects that user master still need support. I’ll have it shortly.
Sections are collapsed by default (well and are collapsable) 
The URL is updated when you select versions and do a diff so you can just copy that direct URL

So now the URL is

http://vdiff.notsoclever.cc/diff/Atmosphere/atmosphere/project-2.1.0/project-2.2.0-RC3

Which I think is more intuitive and looks better.  I expect this format to be the final one.

**Pull request merged**
